

# valid zips note Virginia and DC overlap
# good reference 2012-06-03 http://www.mongabay.com/igapo/zip_codes/
dZipRange4State = \
    dict( (
      ( 'Washington DC',        ( { 'min' : '20000', 'max' : '20599' } ) ),
      ( 'Alabama',              ( { 'min' : '35000', 'max' : '36999' } ) ),
      ( 'Alaska',               ( { 'min' : '99500', 'max' : '99999' } ) ),
      ( 'American Samoa',       ( { 'min' : '96799', 'max' : '96799' } ) ),
      ( 'Arizona',              ( { 'min' : '85000', 'max' : '86999' } ) ),
      ( 'Arkansas',             ( { 'min' : '71600', 'max' : '72999' } ) ),
      ( 'California',           ( { 'min' : '90000', 'max' : '96699' } ) ),
      ( 'Colorado',             ( { 'min' : '80000', 'max' : '81999' } ) ),
      ( 'Connecticut',          ( { 'min' : '06000', 'max' : '06999' } ) ),
      ( 'Delaware',             ( { 'min' : '19700', 'max' : '19999' } ) ),
      ( 'District of Columbia', ( { 'min' : '20000', 'max' : '20599' } ) ),
      ( 'Florida',              ( { 'min' : '32000', 'max' : '34999' } ) ),
      ( 'Georgia',              ( { 'min' : '30000', 'max' : '31999' } ) ),
      ( 'Guam',                 ( { 'min' : '96910', 'max' : '96932' } ) ),
      ( 'Hawaii',               ( { 'min' : '96700', 'max' : '96999' } ) ),
      ( 'Idaho',                ( { 'min' : '83200', 'max' : '83999' } ) ),
      ( 'Illinois',             ( { 'min' : '60000', 'max' : '62999' } ) ),
      ( 'Indiana',              ( { 'min' : '46000', 'max' : '47999' } ) ),
      ( 'Iowa',                 ( { 'min' : '50000', 'max' : '52999' } ) ),
      ( 'Kansas',               ( { 'min' : '66000', 'max' : '67999' } ) ),
      ( 'Kentucky',             ( { 'min' : '40000', 'max' : '42999' } ) ),
      ( 'Louisiana',            ( { 'min' : '70000', 'max' : '71599' } ) ),
      ( 'Maine',                ( { 'min' : '03900', 'max' : '04999' } ) ),
      ( 'Maryland',             ( { 'min' : '20600', 'max' : '21999' } ) ),
      ( 'Massachusetts',        ( { 'min' : '01000', 'max' : '02799' } ) ),
      ( 'Michigan',             ( { 'min' : '48000', 'max' : '49999' } ) ),
      ( 'Minnesota',            ( { 'min' : '55000', 'max' : '56999' } ) ),
      ( 'Mississippi',          ( { 'min' : '38600', 'max' : '39999' } ) ),
      ( 'Missouri',             ( { 'min' : '63000', 'max' : '65999' } ) ),
      ( 'Montana',              ( { 'min' : '59000', 'max' : '59999' } ) ),
      ( 'Nebraska',             ( { 'min' : '68000', 'max' : '69999' } ) ),
      ( 'Nevada',               ( { 'min' : '88900', 'max' : '89999' } ) ),
      ( 'New Hampshire',        ( { 'min' : '03000', 'max' : '03899' } ) ),
      ( 'New Jersey',           ( { 'min' : '07000', 'max' : '08999' } ) ),
      ( 'New Mexico',           ( { 'min' : '87000', 'max' : '88899' } ) ),
      ( 'New York',             ( { 'min' : '10000', 'max' : '14999' } ) ),
      ( 'North Carolina',       ( { 'min' : '27000', 'max' : '28999' } ) ),
      ( 'North Dakota',         ( { 'min' : '58000', 'max' : '58999' } ) ),
      ( 'Northern Mariana Islands',
                                ( { 'min' : '96950', 'max' : '96952' } ) ),
      ( 'Ohio',                 ( { 'min' : '43000', 'max' : '45999' } ) ),
      ( 'Oklahoma',             ( { 'min' : '73000', 'max' : '74999' } ) ),
      ( 'Oregon',               ( { 'min' : '97000', 'max' : '97999' } ) ),
      ( 'Pennsylvania',         ( { 'min' : '15000', 'max' : '19699' } ) ),
      ( 'Puerto Rico',          ( { 'min' : '00600', 'max' : '00999' } ) ),
      ( 'Rhode Island',         ( { 'min' : '02800', 'max' : '02999' } ) ),
      ( 'South Carolina',       ( { 'min' : '29000', 'max' : '29999' } ) ),
      ( 'South Dakota',         ( { 'min' : '57000', 'max' : '57999' } ) ),
      ( 'Tennessee',            ( { 'min' : '37000', 'max' : '38599' } ) ),
      ( 'Texas',                ( { 'min' : '75000', 'max' : '79999' } ) ),
      ( 'Utah',                 ( { 'min' : '84000', 'max' : '84999' } ) ),
      ( 'Vermont',              ( { 'min' : '05000', 'max' : '05999' } ) ),
      ( 'Virginia',             ( { 'min' : '22000', 'max' : '24699' } ) ),
      ( 'Virgin Islands',       ( { 'min' : '00801', 'max' : '00851' } ) ),
      ( 'Washington',           ( { 'min' : '98000', 'max' : '99499' } ) ),
      ( 'West Virginia',        ( { 'min' : '24700', 'max' : '26999' } ) ),
      ( 'Wisconsin',            ( { 'min' : '53000', 'max' : '54999' } ) ),
      ( 'Wyoming',              ( { 'min' : '82000', 'max' : '83199' } ) ) ) )

# http://en.wikipedia.org/wiki/ZIP_code
dZipRange4State['Virginia' ]['more'] = [{ 'min' : '20100', 'max' : '20199'}]
dZipRange4State['New York' ]['more'] = [{ 'min' : '06390', 'max' : '06399'}]
dZipRange4State['Texas'    ]['more'] = [{ 'min' : '88500', 'max' : '88599'}]
dZipRange4State['Arkansas' ]['more'] = [{ 'min' : '65733', 'max' : '65733'}]
dZipRange4State['Tennessee']['more'] = [{ 'min' : '42223', 'max' : '42223'}]



# updates 2015-01-08
# fetched from http://www.apoaddress.com/aponumber.html
# dead
# check http://www.freebizadsweb.com/apofpolist.asp
# defunct
# more up to date http://www5.apobox.com/zip_restrictions.php
# not found
# 09011 09372 & 96303 are kludges, not verified
#

dApoZipCountry = \
    {   '09007' : 'Germany',
        '09009' : 'Germany',
        '09011' : 'Germany',
        '09012' : 'Germany',
        '09013' : 'Germany',
        '09014' : 'Germany',
        '09021' : 'Germany',
        '09028' : 'Germany',
        '09031' : 'Germany',
        '09033' : 'Germany',
        '09034' : 'Germany',
        '09036' : 'Germany',
        '09042' : 'Germany',
        '09045' : 'Germany',
        '09046' : 'Germany',
        '09050' : 'Germany',
        '09053' : 'Germany',
        '09054' : 'Germany',
        '09056' : 'Germany',
        '09058' : 'Germany',
        '09059' : 'Germany',
        '09060' : 'Germany',
        '09063' : 'Germany',
        '09067' : 'Germany',
        '09069' : 'Germany',
        '09074' : 'Germany',
        '09076' : 'Germany',
        '09080' : 'Germany',
        '09081' : 'Germany',
        '09086' : 'Germany',
        '09089' : 'Germany',
        '09090' : 'Germany',
        '09094' : 'Germany',
        '09095' : 'Germany',
        '09096' : 'Germany',
        '09098' : 'Germany',
        '09099' : 'Germany',
        '09100' : 'Germany',
        '09102' : 'Germany',
        '09103' : 'Germany',
        '09104' : 'Germany',
        '09107' : 'Germany',
        '09110' : 'Germany',
        '09112' : 'Germany',
        '09114' : 'Germany',
        '09123' : 'Germany',
        '09126' : 'Germany',
        '09128' : 'Germany',
        '09131' : 'Germany',
        '09136' : 'Germany',
        '09137' : 'Germany',
        '09138' : 'Germany',
        '09139' : 'Germany',
        '09140' : 'Germany',
        '09142' : 'Germany',
        '09143' : 'Germany',
        '09154' : 'Germany',
        '09165' : 'Germany',
        '09166' : 'Germany',
        '09169' : 'Germany',
        '09172' : 'Germany',
        '09173' : 'Germany',
        '09175' : 'Germany',
        '09177' : 'Germany',
        '09180' : 'Germany',
        '09182' : 'Germany',
        '09183' : 'Germany',
        '09185' : 'Germany',
        '09186' : 'Germany',
        '09211' : 'Germany',
        '09212' : 'Germany',
        '09213' : 'Germany',
        '09214' : 'Germany',
        '09225' : 'Germany',
        '09226' : 'Germany',
        '09227' : 'Germany',
        '09229' : 'Germany',
        '09237' : 'Germany',
        '09244' : 'Germany',
        '09245' : 'Germany',
        '09250' : 'Germany',
        '09252' : 'Germany',
        '09262' : 'Germany',
        '09263' : 'Germany',
        '09264' : 'Germany',
        '09265' : 'Germany',
        '09266' : 'Germany',
        '09267' : 'Germany',
        '09302' : 'Kuwait',
        '09303' : 'Kuwait',
        '09304' : 'Kuwait',
        '09305' : 'Kuwait',
        '09306' : 'Kuwait',
        '09306' : 'Kuwait',
        '09309' : 'Qatar',
        '09310' : frozenset( ( 'Afghanistan', 'Iraq' ) ),
        '09312' : 'Iraq',
        '09313' : 'Iraq',
        '09314' : 'Afghanistan',
        '09315' : 'Iraq',
        '09320' : 'Afghanistan',
        '09330' : 'Kuwait',
        '09331' : 'Iraq',
        '09332' : 'Iraq',
        '09333' : 'Iraq',
        '09334' : 'Iraq',
        '09336' : 'Kuwait',
        '09337' : 'Kuwait',
        '09338' : 'Iraq',
        '09340' : 'Kosovo',
        '09342' : 'Iraq',
        '09344' : 'Iraq',
        '09347' : 'Iraq',
        '09348' : 'Iraq',
        '09351' : 'Iraq',
        '09354' : frozenset( ( 'Afghanistan', 'Germany' ) ),
        '09355' : 'Afghanistan',
        '09356' : 'Afghanistan',
        '09359' : 'Iraq',
        '09366' : 'Kuwait',
        '09368' : 'Iraq',
        '09372' : 'Afghanistan',
        '09375' : 'Iraq',
        '09378' : 'Iraq',
        '09384' : 'Iraq',
        '09391' : 'Iraq',
        '09393' : 'Iraq',
        '09397' : 'Germany',
        '09399' : 'Germany',
        '09421' : 'United Kingdom',
        '09432' : 'Iraq',
        '09447' : 'United Kingdom',
        '09454' : 'United Kingdom',
        '09456' : 'United Kingdom',
        '09459' : 'United Kingdom',
        '09461' : 'United Kingdom',
        '09463' : 'United Kingdom',
        '09464' : 'United Kingdom',
        '09468' : 'United Kingdom',
        '09469' : 'United Kingdom',
        '09470' : 'United Kingdom',
        '09494' : 'United Kingdom',
        '09496' : 'United Kingdom',
        '09498' : 'United Kingdom',
        '09508' : 'Cuba',
        '09601' : 'Italy',
        '09603' : 'Italy',
        '09604' : 'Italy',
        '09609' : 'Italy',
        '09610' : 'Italy',
        '09612' : 'Italy',
        '09613' : 'Italy',
        '09617' : 'Italy',
        '09618' : 'Italy',
        '09619' : 'Italy',
        '09620' : 'Italy',
        '09621' : 'Italy',
        '09622' : 'Italy',
        '09623' : 'Italy',
        '09624' : 'Italy',
        '09625' : 'Italy',
        '09626' : 'Italy',
        '09627' : 'Italy',
        '09628' : 'Italy',
        '09630' : 'Italy',
        '09631' : 'Italy',
        '09636' : 'Italy',
        '09638' : 'Italy',
        '09642' : 'Spain',
        '09643' : 'Spain',
        '09644' : 'Spain',
        '09645' : 'Spain',
        '09647' : 'Spain',
        '09649' : 'Spain',
        '09703' : 'Netherlands',
        '09704' : 'Greenland',
        '09705' : 'Belgium',
        '09706' : 'Norway',
        '09707' : 'Norway',
        '09708' : 'Belgium',
        '09709' : 'Netherlands',
        '09710' : 'Belgium',
        '09711' : 'Netherlands',
        '09713' : 'Belgium',
        '09714' : 'Belgium',
        '09715' : 'Netherlands',
        '09716' : 'Denmark',
        '09717' : 'Netherlands',
        '09718' : 'Morocco',
        '09720' : 'Portugal',
        '09721' : frozenset( ('Finland', 'Russian Federation', 'Switzerland' ) ),
        '09722' : 'Denmark',
        '09723' : 'Finland',
        '09724' : 'Belgium',
        '09725' : 'Iceland',
        '09726' : 'Portugal',
        '09728' : 'Iceland',
        '09732' : 'Canada',
        '09733' : 'Canada',
        '09734' : 'Iraq',
        '09735' : 'Canada',
        '09749' : 'Romania',
        '09777' : 'France',
        '09788' : 'Bosnia',
        '09779' : 'Bosnia',
        '09780' : 'Bosnia',
        '09789' : 'Bosnia',
        '09790' : 'Monaco',
        '09791' : 'France',
        '09793' : 'Hungary',
        '09802' : 'Saudi Arabia',
        '09803' : 'Saudi Arabia',
        '09809' : 'Saudi Arabia',
        '09810' : 'Saudi Arabia',
        '09811' : 'Saudi Arabia',
        '09812' : 'Pakistan',
        '09814' : 'Pakistan',
        '09819' : 'Turkey',
        '09821' : 'Turkey',
        '09822' : 'Turkey',
        '09823' : 'Turkey',
        '09824' : 'Adana Turkey',
        '09827' : 'Turkey',
        '09828' : 'Congo',
        '09830' : 'Israel',
        '09831' : 'Kenya',
        '09832' : 'Egypt',
        '09833' : 'Egypt',
        '09834' : 'Bahrain',
        '09835' : 'Egypt',
        '09836' : 'Cyprus',
        '09837' : 'United Arab Emirates',
        '09838' : 'Bahrain',
        '09839' : 'Egypt',
        '09841' : 'Greece',
        '09842' : 'Greece',
        '09844' : 'Greece',
        '09852' : 'Saudi Arabia',
        '09853' : 'United Arab Emirates',
        '09855' : 'Kuwait',
        '09858' : 'Saudi Arabia',
        '09865' : 'Greece',
        '09868' : 'Egypt',
        '09871' : 'Saudi Arabia',
        '09880' : 'Kuwait',
        '09882' : 'Saudi Arabia',
        '09888' : 'Kuwait',
        '09889' : 'Kuwait',
        '09890' : 'Oman',
        '09892' : 'Jordan',
        '09898' : 'Qatar',
        '34002' : 'Panama',
        '34020' : 'Costa Rica',
        '34021' : 'Nicaragua',
        '34022' : 'Honduras',
        '34023' : 'El Salvador',
        '34024' : 'Guatemala',
        '34025' : 'Belize',
        '34030' : 'Brazil',
        '34031' : 'Peru',
        '34032' : 'Bolivia',
        '34033' : 'Chile',
        '34034' : 'Argentina',
        '34035' : 'Uruguay',
        '34036' : 'Paraguay',
        '34037' : 'Venezuela',
        '34038' : 'Colombia',
        '34039' : 'Ecuador',
        '34040' : 'Puerto Rico',
        '34041' : 'Dominican Republic',
        '34042' : 'Honduras',
        '34050' : 'Puerto Rico',
        '34053' : 'Puerto Rico',
        '34055' : 'Barbados',
        '34058' : 'Bahamas',
        '34076' : 'Ecuador',
        '34078' : 'Haiti',
        '34079' : 'Aruba',
        '96201' : 'South Korea',
        '96203' : 'South Korea',
        '96204' : 'South Korea',
        '96205' : 'South Korea',
        '96206' : 'South Korea',
        '96207' : 'South Korea',
        '96208' : 'South Korea',
        '96212' : 'South Korea',
        '96213' : 'South Korea',
        '96214' : 'South Korea',
        '96215' : 'South Korea',
        '96217' : 'South Korea',
        '96218' : 'South Korea',
        '96219' : 'South Korea',
        '96220' : 'South Korea',
        '96221' : 'South Korea',
        '96224' : 'South Korea',
        '96251' : 'South Korea',
        '96257' : 'South Korea',
        '96258' : 'South Korea',
        '96259' : 'South Korea',
        '96260' : 'South Korea',
        '96262' : 'South Korea',
        '96264' : 'South Korea',
        '96266' : 'South Korea',
        '96267' : 'South Korea',
        '96269' : 'South Korea',
        '96271' : 'South Korea',
        '96275' : 'South Korea',
        '96276' : 'South Korea',
        '96278' : 'South Korea',
        '96283' : 'South Korea',
        '96284' : 'South Korea',
        '96297' : 'South Korea',
        '96303' : 'Japan',
        '96306' : 'Japan',
        '96309' : 'Japan',
        '96310' : 'Japan',
        '96311' : 'Japan',
        '96313' : 'Japan',
        '96319' : 'Japan',
        '96321' : 'Japan',
        '96322' : 'Japan',
        '96323' : 'Japan',
        '96326' : 'Japan',
        '96328' : 'Japan',
        '96330' : 'Japan',
        '96336' : 'Japan',
        '96337' : 'Japan',
        '96338' : 'Japan',
        '96339' : 'Japan',
        '96343' : 'Japan',
        '96347' : 'Japan',
        '96348' : 'Japan',
        '96349' : 'Japan',
        '96350' : 'Japan',
        '96351' : 'Japan',
        '96362' : 'Japan',
        '96365' : 'Japan',
        '96367' : 'Japan',
        '96368' : 'Japan',
        '96370' : 'Japan',
        '96372' : 'Japan',
        '96373' : 'Japan',
        '96374' : 'Japan',
        '96375' : 'Japan',
        '96376' : 'Japan',
        '96377' : 'Japan',
        '96378' : 'Japan',
        '96379' : 'Japan',
        '96384' : 'Japan',
        '96386' : 'Japan',
        '96387' : 'Japan',
        '96388' : 'Japan',
        '96401' : 'Australia',
        '96490' : 'British Indian Ocean Territory',
        '96507' : 'Singapore',
        '96511' : 'Canada',
        '96515' : 'Philippines',
        '96517' : 'Philippines',
        '96520' : 'Indonesia',
        '96521' : 'Hong Kong',
        '96522' : 'Hong Kong',
        '96530' : 'Australia',
        '96531' : 'New Zealand',
        '96534' : 'Singapore',
        '96535' : 'Malaysia',
        '96536' : 'Guam',
        '96537' : 'Guam',
        '96538' : 'Guam',
        '96540' : 'Guam',
        '96541' : 'Guam',
        '96542' : 'Guam',
        '96543' : 'Guam',
        '96546' : 'Thailand',
        '96548' : 'Australia',
        '96549' : 'Australia',
        '96551' : 'Australia',
        '96553' : 'Australia',
        '96554' : 'Australia',
        '96555' : 'Marshall Island',
        '96557' : 'Marshall Island',
        '96595' : 'British Indian Ocean Territory',
        '96598' : 'Antarctica',
        '96599' : 'Antarctica',
        '96602' : 'Japan',
        '96603' : 'Japan',
        '96604' : 'Japan',
        '96606' : 'Japan',
        '96613' : 'Kuwait' }






tStatesCounties = (
( 'Alabama', (
    "Autauga",
    "Baldwin",
    "Barbour",
    "Bibb",
    "Blount",
    "Bullock",
    "Butler",
    "Calhoun",
    "Chambers",
    "Cherokee",
    "Chilton",
    "Choctaw",
    "Clarke",
    "Clay",
    "Cleburne",
    "Coffee",
    "Colbert",
    "Conecuh",
    "Coosa",
    "Covington",
    "Crenshaw",
    "Cullman",
    "Dale",
    "Dallas",
    "DeKalb",
    "Elmore",
    "Escambia",
    "Etowah",
    "Fayette",
    "Franklin",
    "Geneva",
    "Greene",
    "Hale",
    "Henry",
    "Houston",
    "Jackson",
    "Jefferson",
    "Lamar",
    "Lauderdale",
    "Lawrence",
    "Lee",
    "Limestone",
    "Lowndes",
    "Macon",
    "Madison",
    "Marengo",
    "Marion",
    "Marshall",
    "Mobile",
    "Monroe",
    "Montgomery",
    "Morgan",
    "Perry",
    "Pickens",
    "Pike",
    "Randolph",
    "Russell",
    "Shelby",
    "St. Clair",
    "Sumter",
    "Talladega",
    "Tallapoosa",
    "Tuscaloosa",
    "Walker",
    "Washington",
    "Wilcox",
    "Winston" ) ),
( 'Alaska', (
    "Anchorage Borough",
    "Bethel Census Area",
    "Bristol Bay Borough",
    "Dillingham Census Area",
    "Fairbanks North Star Borough",
    "Haines Borough",
    "Juneau Borough",
    "Kenai Peninsula Borough",
    "Ketchikan Gateway Borough",
    "Kodiak Island Borough",
    "Matanuska-Susitna Borough",
    "Nome Census Area",
    "North Slope Borough",
    "Prince of Wales-Outer Ketchikan Census A",
    "Sitka Borough",
    "Skagway-Hoonah-Angoon Census Area",
    "Southeast Fairbanks Census Area",
    "Valdez-Cordova Census Area",
    "Wade Hampton Census Area",
    "Wrangell-Petersburg Census Area",
    "Yakutat Borough",
    "Yukon-Koyukuk Census Area" ) ),
( 'Arizona', (
    "Apache",
    "Cochise",
    "Coconino",
    "Gila",
    "Graham",
    "Greenlee",
    "La Paz",
    "Maricopa",
    "Mohave",
    "Navajo",
    "Pima",
    "Pinal",
    "Santa Cruz",
    "Yavapai",
    "Yuma" ) ),
( 'Arkansas', (
    "Arkansas",
    "Ashley",
    "Baxter",
    "Benton",
    "Boone",
    "Bradley",
    "Calhoun",
    "Carroll",
    "Chicot",
    "Clark",
    "Clay",
    "Cleburne",
    "Cleveland",
    "Columbia",
    "Conway",
    "Craighead",
    "Crawford",
    "Crittenden",
    "Cross",
    "Dallas",
    "Desha",
    "Drew",
    "Faulkner",
    "Franklin",
    "Fulton",
    "Garland",
    "Grant",
    "Greene",
    "Hempstead",
    "Hot Spring",
    "Howard",
    "Independence",
    "Izard",
    "Jackson",
    "Jefferson",
    "Johnson",
    "Lafayette",
    "Lawrence",
    "Lee",
    "Lincoln",
    "Little River",
    "Logan",
    "Lonoke",
    "Madison",
    "Marion",
    "Miller",
    "Mississippi",
    "Monroe",
    "Montgomery",
    "Nevada",
    "Newton",
    "Ouachita",
    "Perry",
    "Phillips",
    "Pike",
    "Poinsett",
    "Polk",
    "Pope",
    "Prairie",
    "Pulaski",
    "Randolph",
    "Saline",
    "Scott",
    "Searcy",
    "Sebastian",
    "Sevier",
    "Sharp",
    "St. Francis",
    "Stone",
    "Union",
    "Van Buren",
    "Washington",
    "White",
    "Woodruff",
    "Yell" ) ),
( 'California', (
    "Alameda",
    "Alpine",
    "Amador",
    "Butte",
    "Calaveras",
    "Colusa",
    "Contra Costa",
    "Del Norte",
    "El Dorado",
    "Fresno",
    "Glenn",
    "Humboldt",
    "Imperial",
    "Inyo",
    "Kern",
    "Kings",
    "Lake",
    "Lassen",
    "Los Angeles",
    "Madera",
    "Marin",
    "Mariposa",
    "Mendocino",
    "Merced",
    "Modoc",
    "Mono",
    "Monterey",
    "Napa",
    "Nevada",
    "Orange",
    "Placer",
    "Plumas",
    "Riverside",
    "Sacramento",
    "San Benito",
    "San Bernardino",
    "San Diego",
    "San Francisco",
    "San Joaquin",
    "San Luis Obispo",
    "San Mateo",
    "Santa Barbara",
    "Santa Clara",
    "Santa Cruz",
    "Shasta",
    "Sierra",
    "Siskiyou",
    "Solano",
    "Sonoma",
    "Stanislaus",
    "Sutter",
    "Tehama",
    "Trinity",
    "Tulare",
    "Tuolumne",
    "Ventura",
    "Yolo",
    "Yuba" ) ),
( 'Colorado', (
    "Adams",
    "Alamosa",
    "Arapahoe",
    "Archuleta",
    "Baca",
    "Bent",
    "Boulder",
    "Broomfield",
    "Chaffee",
    "Cheyenne",
    "Clear Creek",
    "Conejos",
    "Costilla",
    "Crowley",
    "Custer",
    "Delta",
    "Denver",
    "Dolores",
    "Douglas",
    "Eagle",
    "El Paso",
    "Elbert",
    "Fremont",
    "Garfield",
    "Gilpin",
    "Grand",
    "Gunnison",
    "Hinsdale",
    "Huerfano",
    "Jackson",
    "Jefferson",
    "Kiowa",
    "Kit Carson",
    "La Plata",
    "Lake",
    "Larimer",
    "Las Animas",
    "Lincoln",
    "Logan",
    "Mesa",
    "Mineral",
    "Moffat",
    "Montezuma",
    "Montrose",
    "Morgan",
    "Otero",
    "Ouray",
    "Park",
    "Phillips",
    "Pitkin",
    "Prowers",
    "Pueblo",
    "Rio Blanco",
    "Rio Grande",
    "Routt",
    "Saguache",
    "San Juan",
    "San Miguel",
    "Sedgwick",
    "Summit",
    "Teller",
    "Washington",
    "Weld",
    "Yuma" ) ),
( 'Connecticut', (
    "Fairfield",
    "Hartford",
    "Litchfield",
    "Middlesex",
    "New Haven",
    "New London",
    "Tolland",
    "Windham" ) ),
( 'Delaware', (
    "Kent",
    "New Castle",
    "Sussex" ) ),
( 'Florida', (
    "Alachua",
    "Baker",
    "Bay",
    "Bradford",
    "Brevard",
    "Broward",
    "Calhoun",
    "Charlotte",
    "Citrus",
    "Clay",
    "Collier",
    "Columbia",
    "DeSoto",
    "Dixie",
    "Duval",
    "Escambia",
    "Flagler",
    "Franklin",
    "Gadsden",
    "Gilchrist",
    "Glades",
    "Gulf",
    "Hamilton",
    "Hardee",
    "Hendry",
    "Hernando",
    "Highlands",
    "Hillsborough",
    "Holmes",
    "Indian River",
    "Jackson",
    "Jefferson",
    "Lafayette",
    "Lake",
    "Lee",
    "Leon",
    "Levy",
    "Liberty",
    "Madison",
    "Manatee",
    "Marion",
    "Martin",
    "Miami-Dade",
    "Monroe",
    "Nassau",
    "Okaloosa",
    "Okeechobee",
    "Orange",
    "Osceola",
    "Palm Beach",
    "Pasco",
    "Pinellas",
    "Polk",
    "Putnam",
    "Santa Rosa",
    "Sarasota",
    "Seminole",
    "St. Johns",
    "St. Lucie",
    "Sumter",
    "Suwannee",
    "Taylor",
    "Union",
    "Volusia",
    "Wakulla",
    "Walton",
    "Washington" ) ),
( 'Georgia', (
    "Appling",
    "Atkinson",
    "Bacon",
    "Baker",
    "Baldwin",
    "Banks",
    "Barrow",
    "Bartow",
    "Ben Hill",
    "Berrien",
    "Bibb",
    "Bleckley",
    "Brantley",
    "Brooks",
    "Bryan",
    "Bulloch",
    "Burke",
    "Butts",
    "Calhoun",
    "Camden",
    "Candler",
    "Carroll",
    "Catoosa",
    "Charlton",
    "Chatham",
    "Chattahoochee",
    "Chattooga",
    "Cherokee",
    "Clarke",
    "Clay",
    "Clayton",
    "Clinch",
    "Cobb",
    "Coffee",
    "Colquitt",
    "Columbia",
    "Cook",
    "Coweta",
    "Crawford",
    "Crisp",
    "Dade",
    "Dawson",
    "Decatur",
    "DeKalb",
    "Dodge",
    "Dooly",
    "Dougherty",
    "Douglas",
    "Early",
    "Echols",
    "Effingham",
    "Elbert",
    "Emanuel",
    "Evans",
    "Fannin",
    "Fayette",
    "Floyd",
    "Forsyth",
    "Franklin",
    "Fulton",
    "Gilmer",
    "Glascock",
    "Glynn",
    "Gordon",
    "Grady",
    "Greene",
    "Gwinnett",
    "Habersham",
    "Hall",
    "Hancock",
    "Haralson",
    "Harris",
    "Hart",
    "Heard",
    "Henry",
    "Houston",
    "Irwin",
    "Jackson",
    "Jasper",
    "Jeff Davis",
    "Jefferson",
    "Jenkins",
    "Johnson",
    "Jones",
    "Lamar",
    "Lanier",
    "Laurens",
    "Lee",
    "Liberty",
    "Lincoln",
    "Long",
    "Lowndes",
    "Lumpkin",
    "Macon",
    "Madison",
    "Marion",
    "McDuffie",
    "McIntosh",
    "Meriwether",
    "Miller",
    "Mitchell",
    "Monroe",
    "Montgomery",
    "Morgan",
    "Murray",
    "Muscogee",
    "Newton",
    "Oconee",
    "Oglethorpe",
    "Paulding",
    "Peach",
    "Pickens",
    "Pierce",
    "Pike",
    "Polk",
    "Pulaski",
    "Putnam",
    "Quitman",
    "Rabun",
    "Randolph",
    "Richmond",
    "Rockdale",
    "Schley",
    "Screven",
    "Seminole",
    "Spalding",
    "Stephens",
    "Stewart",
    "Sumter",
    "Talbot",
    "Taliaferro",
    "Tattnall",
    "Taylor",
    "Telfair",
    "Terrell",
    "Thomas",
    "Tift",
    "Toombs",
    "Towns",
    "Treutlen",
    "Troup",
    "Turner",
    "Twiggs",
    "Union",
    "Upson",
    "Walker",
    "Walton",
    "Ware",
    "Warren",
    "Washington",
    "Wayne",
    "Webster",
    "Wheeler",
    "White",
    "Whitfield",
    "Wilcox",
    "Wilkes",
    "Wilkinson",
    "Worth" ) ),
( 'Hawaii', (
    "Hawaii",
    "Honolulu",
    "Kalawao",
    "Kauai",
    "Maui" ) ),
( 'Idaho', (
    "Ada",
    "Adams",
    "Bannock",
    "Bear Lake",
    "Benewah",
    "Bingham",
    "Blaine",
    "Boise",
    "Bonner",
    "Bonneville",
    "Boundary",
    "Butte",
    "Camas",
    "Canyon",
    "Caribou",
    "Cassia",
    "Clark",
    "Clearwater",
    "Custer",
    "Elmore",
    "Franklin",
    "Fremont",
    "Gem",
    "Gooding",
    "Idaho",
    "Jefferson",
    "Jerome",
    "Kootenai",
    "Latah",
    "Lemhi",
    "Lewis",
    "Lincoln",
    "Madison",
    "Minidoka",
    "Nez Perce",
    "Oneida",
    "Owyhee",
    "Payette",
    "Power",
    "Shoshone",
    "Teton",
    "Twin Falls",
    "Valley",
    "Washington" ) ),
( 'Illinois', (
    "Adams",
    "Alexander",
    "Bond",
    "Boone",
    "Brown",
    "Bureau",
    "Calhoun",
    "Carroll",
    "Cass",
    "Champaign",
    "Christian",
    "Clark",
    "Clay",
    "Clinton",
    "Coles",
    "Cook",
    "Crawford",
    "Cumberland",
    "De Witt",
    "DeKalb",
    "Douglas",
    "DuPage",
    "Edgar",
    "Edwards",
    "Effingham",
    "Fayette",
    "Ford",
    "Franklin",
    "Fulton",
    "Gallatin",
    "Greene",
    "Grundy",
    "Hamilton",
    "Hancock",
    "Hardin",
    "Henderson",
    "Henry",
    "Iroquois",
    "Jackson",
    "Jasper",
    "Jefferson",
    "Jersey",
    "Jo Daviess",
    "Johnson",
    "Kane",
    "Kankakee",
    "Kendall",
    "Knox",
    "La Salle",
    "Lake",
    "Lawrence",
    "Lee",
    "Livingston",
    "Logan",
    "Macon",
    "Macoupin",
    "Madison",
    "Marion",
    "Marshall",
    "Mason",
    "Massac",
    "McDonough",
    "McHenry",
    "McLean",
    "Menard",
    "Mercer",
    "Monroe",
    "Montgomery",
    "Morgan",
    "Moultrie",
    "Ogle",
    "Peoria",
    "Perry",
    "Piatt",
    "Pike",
    "Pope",
    "Pulaski",
    "Putnam",
    "Randolph",
    "Richland",
    "Rock Island",
    "Saline",
    "Sangamon",
    "Schuyler",
    "Scott",
    "Shelby",
    "St. Clair",
    "Stark",
    "Stephenson",
    "Tazewell",
    "Union",
    "Vermilion",
    "Wabash",
    "Warren",
    "Washington",
    "Wayne",
    "White",
    "Whiteside",
    "Will",
    "Williamson",
    "Winnebago",
    "Woodford" ) ),
    ( 'Indiana', (
    "Adams",
    "Allen",
    "Bartholomew",
    "Benton",
    "Blackford",
    "Boone",
    "Brown",
    "Carroll",
    "Cass",
    "Clark",
    "Clay",
    "Clinton",
    "Crawford",
    "Daviess",
    "De Kalb",
    "Dearborn",
    "Decatur",
    "Delaware",
    "Dubois",
    "Elkhart",
    "Fayette",
    "Floyd",
    "Fountain",
    "Franklin",
    "Fulton",
    "Gibson",
    "Grant",
    "Greene",
    "Hamilton",
    "Hancock",
    "Harrison",
    "Hendricks",
    "Henry",
    "Howard",
    "Huntington",
    "Jackson",
    "Jasper",
    "Jay",
    "Jefferson",
    "Jennings",
    "Johnson",
    "Knox",
    "Kosciusko",
    "La Porte",
    "Lagrange",
    "Lake",
    "Lawrence",
    "Madison",
    "Marion",
    "Marshall",
    "Martin",
    "Miami",
    "Monroe",
    "Montgomery",
    "Morgan",
    "Newton",
    "Noble",
    "Ohio",
    "Orange",
    "Owen",
    "Parke",
    "Perry",
    "Pike",
    "Porter",
    "Posey",
    "Pulaski",
    "Putnam",
    "Randolph",
    "Ripley",
    "Rush",
    "Scott",
    "Shelby",
    "Spencer",
    "St. Joseph",
    "Starke",
    "Steuben",
    "Sullivan",
    "Switzerland",
    "Tippecanoe",
    "Tipton",
    "Union",
    "Vanderburgh",
    "Vermillion",
    "Vigo",
    "Wabash",
    "Warren",
    "Warrick",
    "Washington",
    "Wayne",
    "Wells",
    "White",
    "Whitley" ) ),
( 'Iowa', (
    "Adair",
    "Adams",
    "Allamakee",
    "Appanoose",
    "Audubon",
    "Benton",
    "Black Hawk",
    "Boone",
    "Bremer",
    "Buchanan",
    "Buena Vista",
    "Butler",
    "Calhoun",
    "Carroll",
    "Cass",
    "Cedar",
    "Cerro Gordo",
    "Cherokee",
    "Chickasaw",
    "Clarke",
    "Clay",
    "Clayton",
    "Clinton",
    "Crawford",
    "Dallas",
    "Davis",
    "Decatur",
    "Delaware",
    "Des Moines",
    "Dickinson",
    "Dubuque",
    "Emmet",
    "Fayette",
    "Floyd",
    "Franklin",
    "Fremont",
    "Greene",
    "Grundy",
    "Guthrie",
    "Hamilton",
    "Hancock",
    "Hardin",
    "Harrison",
    "Henry",
    "Howard",
    "Humboldt",
    "Ida",
    "Iowa",
    "Jackson",
    "Jasper",
    "Jefferson",
    "Johnson",
    "Jones",
    "Keokuk",
    "Kossuth",
    "Lee",
    "Linn",
    "Louisa",
    "Lucas",
    "Lyon",
    "Madison",
    "Mahaska",
    "Marion",
    "Marshall",
    "Mills",
    "Mitchell",
    "Monona",
    "Monroe",
    "Montgomery",
    "Muscatine",
    "O'Brien",
    "Osceola",
    "Page",
    "Palo Alto",
    "Plymouth",
    "Pocahontas",
    "Polk",
    "Pottawattamie",
    "Poweshiek",
    "Ringgold",
    "Sac",
    "Scott",
    "Shelby",
    "Sioux",
    "Story",
    "Tama",
    "Taylor",
    "Union",
    "Van Buren",
    "Wapello",
    "Warren",
    "Washington",
    "Wayne",
    "Webster",
    "Winnebago",
    "Winneshiek",
    "Woodbury",
    "Worth",
    "Wright" ) ),
( 'Kansas', (
    "Allen",
    "Anderson",
    "Atchison",
    "Barber",
    "Barton",
    "Bourbon",
    "Brown",
    "Butler",
    "Chase",
    "Chautauqua",
    "Cherokee",
    "Cheyenne",
    "Clark",
    "Clay",
    "Cloud",
    "Coffey",
    "Comanche",
    "Cowley",
    "Crawford",
    "Decatur",
    "Dickinson",
    "Doniphan",
    "Douglas",
    "Edwards",
    "Elk",
    "Ellis",
    "Ellsworth",
    "Finney",
    "Ford",
    "Franklin",
    "Geary",
    "Gove",
    "Graham",
    "Grant",
    "Gray",
    "Greeley",
    "Greenwood",
    "Hamilton",
    "Harper",
    "Harvey",
    "Haskell",
    "Hodgeman",
    "Jackson",
    "Jefferson",
    "Jewell",
    "Johnson",
    "Kearny",
    "Kingman",
    "Kiowa",
    "Labette",
    "Lane",
    "Leavenworth",
    "Lincoln",
    "Linn",
    "Logan",
    "Lyon",
    "Marion",
    "Marshall",
    "McPherson",
    "Meade",
    "Miami",
    "Mitchell",
    "Montgomery",
    "Morris",
    "Morton",
    "Nemaha",
    "Neosho",
    "Ness",
    "Norton",
    "Osage",
    "Osborne",
    "Ottawa",
    "Pawnee",
    "Phillips",
    "Pottawatomie",
    "Pratt",
    "Rawlins",
    "Reno",
    "Republic",
    "Rice",
    "Riley",
    "Rooks",
    "Rush",
    "Russell",
    "Saline",
    "Scott",
    "Sedgwick",
    "Seward",
    "Shawnee",
    "Sheridan",
    "Sherman",
    "Smith",
    "Stafford",
    "Stanton",
    "Stevens",
    "Sumner",
    "Thomas",
    "Trego",
    "Wabaunsee",
    "Wallace",
    "Washington",
    "Wichita",
    "Wilson",
    "Woodson",
    "Wyandotte" ) ),
( 'Kentucky', (
    "Adair",
    "Allen",
    "Anderson",
    "Ballard",
    "Barren",
    "Bath",
    "Bell",
    "Boone",
    "Bourbon",
    "Boyd",
    "Boyle",
    "Bracken",
    "Breathitt",
    "Breckenridge",
    "Bullitt",
    "Butler",
    "Caldwell",
    "Calloway",
    "Campbell",
    "Carlisle",
    "Carroll",
    "Carter",
    "Casey",
    "Christian",
    "Clark",
    "Clay",
    "Clinton",
    "Crittenden",
    "Cumberland",
    "Daviess",
    "Edmonson",
    "Elliott",
    "Estill",
    "Fayette",
    "Fleming",
    "Floyd",
    "Franklin",
    "Fulton",
    "Gallatin",
    "Garrard",
    "Grant",
    "Graves",
    "Grayson",
    "Green",
    "Greenup",
    "Hancock",
    "Hardin",
    "Harlan",
    "Harrison",
    "Hart",
    "Henderson",
    "Henry",
    "Hickman",
    "Hopkins",
    "Jackson",
    "Jefferson",
    "Jessamine",
    "Johnson",
    "Kenton",
    "Knott",
    "Knox",
    "Larue",
    "Laurel",
    "Lawrence",
    "Lee",
    "Leslie",
    "Letcher",
    "Lewis",
    "Lincoln",
    "Livingston",
    "Logan",
    "Lyon",
    "Madison",
    "Magoffin",
    "Marion",
    "Marshall",
    "Martin",
    "Mason",
    "McCracken",
    "McCreary",
    "McLean",
    "Meade",
    "Menifee",
    "Mercer",
    "Metcalfe",
    "Monroe",
    "Montgomery",
    "Morgan",
    "Muhlenberg",
    "Nelson",
    "Nicholas",
    "Ohio",
    "Oldham",
    "Owen",
    "Owsley",
    "Pendleton",
    "Perry",
    "Pike",
    "Powell",
    "Pulaski",
    "Robertson",
    "Rockcastle",
    "Rowan",
    "Russell",
    "Scott",
    "Shelby",
    "Simpson",
    "Spencer",
    "Taylor",
    "Todd",
    "Trigg",
    "Trimble",
    "Union",
    "Warren",
    "Washington",
    "Wayne",
    "Webster",
    "Whitley",
    "Wolfe",
    "Woodford" ) ),
( 'Louisiana', (
    "Acadia",
    "Allen",
    "Ascension",
    "Assumption",
    "Avoyelles",
    "Beauregard",
    "Bienville",
    "Bossier",
    "Caddo",
    "Calcasieu",
    "Caldwell",
    "Cameron",
    "Catahoula",
    "Claiborne",
    "Concordia",
    "De Soto",
    "East Baton Rouge",
    "East Carroll",
    "East Feliciana",
    "Evangeline",
    "Franklin",
    "Grant",
    "Iberia",
    "Iberville",
    "Jackson",
    "Jefferson Davis",
    "Jefferson",
    "La Salle",
    "Lafayette",
    "Lafourche",
    "Lincoln",
    "Livingston",
    "Madison",
    "Morehouse",
    "Natchitoches",
    "Orleans",
    "Ouachita",
    "Plaquemines",
    "Pointe Coupee",
    "Rapides",
    "Red River",
    "Richland",
    "Sabine",
    "St. Bernard",
    "St. Charles",
    "St. Helena",
    "St. James",
    "St. John the Baptist",
    "St. Landry",
    "St. Martin",
    "St. Mary",
    "St. Tammany",
    "Tangipahoa",
    "Tensas",
    "Terrebonne",
    "Union",
    "Vermilion",
    "Vernon",
    "Washington",
    "Webster",
    "West Baton Rouge",
    "West Carroll",
    "West Feliciana",
    "Winn" ) ),
( 'Maine', (
    "Androscoggin",
    "Aroostook",
    "Cumberland",
    "Franklin",
    "Hancock",
    "Kennebec",
    "Knox",
    "Lincoln",
    "Oxford",
    "Penobscot",
    "Piscataquis",
    "Sagadahoc",
    "Somerset",
    "Waldo",
    "Washington",
    "York" ) ),
( 'Maryland', (
    "Allegany",
    "Anne Arundel",
    "Baltimore City",
    "Baltimore",
    "Calvert",
    "Caroline",
    "Carroll",
    "Cecil",
    "Charles",
    "Dorchester",
    "Frederick",
    "Garrett",
    "Harford",
    "Howard",
    "Kent",
    "Montgomery",
    "Prince George's",
    "Queen Anne's",
    "Somerset",
    "St. Mary's",
    "Talbot",
    "Washington",
    "Wicomico",
    "Worcester" ) ),
( 'Massachusetts', (
    "Barnstable",
    "Berkshire",
    "Bristol",
    "Dukes",
    "Essex",
    "Franklin",
    "Hampden",
    "Hampshire",
    "Middlesex",
    "Nantucket",
    "Norfolk",
    "Plymouth",
    "Suffolk",
    "Worcester" ) ),
( 'Michigan', (
    "Alcona",
    "Alger",
    "Allegan",
    "Alpena",
    "Antrim",
    "Arenac",
    "Baraga",
    "Barry",
    "Bay",
    "Benzie",
    "Berrien",
    "Branch",
    "Calhoun",
    "Cass",
    "Charlevoix",
    "Cheboygan",
    "Chippewa",
    "Clare",
    "Clinton",
    "Crawford",
    "Delta",
    "Dickinson",
    "Eaton",
    "Emmet",
    "Genesee",
    "Gladwin",
    "Gogebic",
    "Grand Traverse",
    "Gratiot",
    "Hillsdale",
    "Houghton",
    "Huron",
    "Ingham",
    "Ionia",
    "Iosco",
    "Iron",
    "Isabella",
    "Jackson",
    "Kalamazoo",
    "Kalkaska",
    "Kent",
    "Keweenaw",
    "Lake",
    "Lapeer",
    "Leelanau",
    "Lenawee",
    "Livingston",
    "Luce",
    "Mackinac",
    "Macomb",
    "Manistee",
    "Marquette",
    "Mason",
    "Mecosta",
    "Menominee",
    "Midland",
    "Missaukee",
    "Monroe",
    "Montcalm",
    "Montmorency",
    "Muskegon",
    "Newaygo",
    "Oakland",
    "Oceana",
    "Ogemaw",
    "Ontonagon",
    "Osceola",
    "Oscoda",
    "Otsego",
    "Ottawa",
    "Presque Isle",
    "Roscommon",
    "Saginaw",
    "Sanilac",
    "Schoolcraft",
    "Shiawassee",
    "St. Clair",
    "St. Joseph",
    "Tuscola",
    "Van Buren",
    "Washtenaw",
    "Wayne",
    "Wexford" ) ),
( 'Minnesota', (
    "Aitkin",
    "Anoka",
    "Becker",
    "Beltrami",
    "Benton",
    "Big Stone",
    "Blue Earth",
    "Brown",
    "Carlton",
    "Carver",
    "Cass",
    "Chippewa",
    "Chisago",
    "Clay",
    "Clearwater",
    "Cook",
    "Cottonwood",
    "Crow Wing",
    "Dakota",
    "Dodge",
    "Douglas",
    "Faribault",
    "Fillmore",
    "Freeborn",
    "Goodhue",
    "Grant",
    "Hennepin",
    "Houston",
    "Hubbard",
    "Isanti",
    "Itasca",
    "Jackson",
    "Kanabec",
    "Kandiyohi",
    "Kittson",
    "Koochiching",
    "Lac qui Parle",
    "Lake of the Woods",
    "Lake",
    "Le Sueur",
    "Lincoln",
    "Lyon",
    "Mahnomen",
    "Marshall",
    "Martin",
    "McLeod",
    "Meeker",
    "Mille Lacs",
    "Morrison",
    "Mower",
    "Murray",
    "Nicollet",
    "Nobles",
    "Norman",
    "Olmsted",
    "Otter Tail",
    "Pennington",
    "Pine",
    "Pipestone",
    "Polk",
    "Pope",
    "Ramsey",
    "Red Lake",
    "Redwood",
    "Renville",
    "Rice",
    "Rock",
    "Roseau",
    "Scott",
    "Sherburne",
    "Sibley",
    "St. Louis",
    "Stearns",
    "Steele",
    "Stevens",
    "Swift",
    "Todd",
    "Traverse",
    "Wabasha",
    "Wadena",
    "Waseca",
    "Washington",
    "Watonwan",
    "Wilkin",
    "Winona",
    "Wright",
    "Yellow Medicine" ) ),
( 'Mississippi', (
    "Adams",
    "Alcorn",
    "Amite",
    "Attala",
    "Benton",
    "Bolivar",
    "Calhoun",
    "Carroll",
    "Chickasaw",
    "Choctaw",
    "Claiborne",
    "Clarke",
    "Clay",
    "Coahoma",
    "Copiah",
    "Covington",
    "DeSoto",
    "Forrest",
    "Franklin",
    "George",
    "Greene",
    "Grenada",
    "Hancock",
    "Harrison",
    "Hinds",
    "Holmes",
    "Humphreys",
    "Issaquena",
    "Itawamba",
    "Jackson",
    "Jasper",
    "Jefferson",
    "Jefferson Davis",
    "Jones",
    "Kemper",
    "Lafayette",
    "Lamar",
    "Lauderdale",
    "Lawrence",
    "Leake",
    "Lee",
    "Leflore",
    "Lincoln",
    "Lowndes",
    "Madison",
    "Marion",
    "Marshall",
    "Monroe",
    "Montgomery",
    "Neshoba",
    "Newton",
    "Noxubee",
    "Oktibbeha",
    "Panola",
    "Pearl River",
    "Perry",
    "Pike",
    "Pontotoc",
    "Prentiss",
    "Quitman",
    "Rankin",
    "Scott",
    "Sharkey",
    "Simpson",
    "Smith",
    "Stone",
    "Sunflower",
    "Tallahatchie",
    "Tate",
    "Tippah",
    "Tishomingo",
    "Tunica",
    "Union",
    "Walthall",
    "Warren",
    "Washington",
    "Wayne",
    "Webster",
    "Wilkinson",
    "Winston",
    "Yalobusha",
    "Yazoo" ) ),
( 'Missouri', (
    "Adair",
    "Andrew",
    "Atchison",
    "Audrain",
    "Barry",
    "Barton",
    "Bates",
    "Benton",
    "Bollinger",
    "Boone",
    "Buchanan",
    "Butler",
    "Caldwell",
    "Callaway",
    "Camden",
    "Cape Girardeau",
    "Carroll",
    "Carter",
    "Cass",
    "Cedar",
    "Chariton",
    "Christian",
    "Clark",
    "Clay",
    "Clinton",
    "Cole",
    "Cooper",
    "Crawford",
    "Dade",
    "Dallas",
    "Daviess",
    "Dent",
    "DeKalb",
    "Douglas",
    "Dunklin",
    "Franklin",
    "Gasconade",
    "Gentry",
    "Greene",
    "Grundy",
    "Harrison",
    "Henry",
    "Hickory",
    "Holt",
    "Howard",
    "Howell",
    "Iron",
    "Jackson",
    "Jasper",
    "Jefferson",
    "Johnson",
    "Knox",
    "Laclede",
    "Lafayette",
    "Lawrence",
    "Lewis",
    "Lincoln",
    "Linn",
    "Livingston",
    "Macon",
    "Madison",
    "Maries",
    "Marion",
    "McDonald",
    "Mercer",
    "Miller",
    "Mississippi",
    "Moniteau",
    "Monroe",
    "Montgomery",
    "Morgan",
    "New Madrid",
    "Newton",
    "Nodaway",
    "Oregon",
    "Osage",
    "Ozark",
    "Pemiscot",
    "Perry",
    "Pettis",
    "Phelps",
    "Pike",
    "Platte",
    "Polk",
    "Pulaski",
    "Putnam",
    "Ralls",
    "Randolph",
    "Ray",
    "Reynolds",
    "Ripley",
    "Saline",
    "Schuyler",
    "Scotland",
    "Scott",
    "Shannon",
    "Shelby",
    "St. Charles",
    "St. Clair",
    "St. Francois",
    "St. Louis city",
    "St. Louis",
    "Ste. Genevieve",
    "Stoddard",
    "Stone",
    "Sullivan",
    "Taney",
    "Texas",
    "Vernon",
    "Warren",
    "Washington",
    "Wayne",
    "Webster",
    "Worth",
    "Wright" ) ),
( 'Montana', (
    "Beaverhead",
    "Big Horn",
    "Blaine",
    "Broadwater",
    "Carbon",
    "Carter",
    "Cascade",
    "Chouteau",
    "Custer",
    "Daniels",
    "Dawson",
    "Deer Lodge",
    "Fallon",
    "Fergus",
    "Flathead",
    "Gallatin",
    "Garfield",
    "Glacier",
    "Golden Valley",
    "Granite",
    "Hill",
    "Jefferson",
    "Judith Basin",
    "Lake",
    "Lewis and Clark",
    "Liberty",
    "Lincoln",
    "Madison",
    "McCone",
    "Meagher",
    "Mineral",
    "Missoula",
    "Musselshell",
    "Park",
    "Petroleum",
    "Phillips",
    "Pondera",
    "Powder River",
    "Powell",
    "Prairie",
    "Ravalli",
    "Richland",
    "Roosevelt",
    "Rosebud",
    "Sanders",
    "Sheridan",
    "Silver Bow",
    "Stillwater",
    "Sweet Grass",
    "Teton",
    "Toole",
    "Treasure",
    "Valley",
    "Wheatland",
    "Wibaux",
    "Yellowstone" ) ),
( 'Nebraska', (
    "Adams",
    "Antelope",
    "Arthur",
    "Banner",
    "Blaine",
    "Boone",
    "Box Butte",
    "Boyd",
    "Brown",
    "Buffalo",
    "Burt",
    "Butler",
    "Cass",
    "Cedar",
    "Chase",
    "Cherry",
    "Cheyenne",
    "Clay",
    "Colfax",
    "Cuming",
    "Custer",
    "Dakota",
    "Dawes",
    "Dawson",
    "Deuel",
    "Dixon",
    "Dodge",
    "Douglas",
    "Dundy",
    "Fillmore",
    "Franklin",
    "Frontier",
    "Furnas",
    "Gage",
    "Garden",
    "Garfield",
    "Gosper",
    "Grant",
    "Greeley",
    "Hall",
    "Hamilton",
    "Harlan",
    "Hayes",
    "Hitchcock",
    "Holt",
    "Hooker",
    "Howard",
    "Jefferson",
    "Johnson",
    "Kearney",
    "Keith",
    "Keya Paha",
    "Kimball",
    "Knox",
    "Lancaster",
    "Lincoln",
    "Logan",
    "Loup",
    "Madison",
    "McPherson",
    "Merrick",
    "Morrill",
    "Nance",
    "Nemaha",
    "Nuckolls",
    "Otoe",
    "Pawnee",
    "Perkins",
    "Phelps",
    "Pierce",
    "Platte",
    "Polk",
    "Red Willow",
    "Richardson",
    "Rock",
    "Saline",
    "Sarpy",
    "Saunders",
    "Scotts Bluff",
    "Seward",
    "Sheridan",
    "Sherman",
    "Sioux",
    "Stanton",
    "Thayer",
    "Thomas",
    "Thurston",
    "Valley",
    "Washington",
    "Wayne",
    "Webster",
    "Wheeler",
    "York" ) ),
( 'Nevada', (
    "Churchill",
    "Clark",
    "Douglas",
    "Elko",
    "Esmeralda",
    "Eureka",
    "Humboldt",
    "Lander",
    "Lincoln",
    "Lyon",
    "Mineral",
    "Nye",
    "Pershing",
    "Storey",
    "Washoe",
    "White Pine" ) ),
( 'New Hampshire', (
    "Belknap",
    "Carroll",
    "Cheshire",
    "Coos",
    "Grafton",
    "Hillsboro",
    "Merrimack",
    "Rockingham",
    "Strafford",
    "Sullivan" ) ),
( 'New Jersey', (
    "Atlantic",
    "Bergen",
    "Burlington",
    "Camden",
    "Cape May",
    "Cumberland",
    "Essex",
    "Gloucester",
    "Hudson",
    "Hunterdon",
    "Mercer",
    "Middlesex",
    "Monmouth",
    "Morris",
    "Ocean",
    "Passaic",
    "Salem",
    "Somerset",
    "Sussex",
    "Union",
    "Warren" ) ),
( 'New Mexico', (
    "Bernalillo",
    "Catron",
    "Chaves",
    "Cibola",
    "Colfax",
    "Curry",
    "DeBaca",
    "Dona Ana",
    "Eddy",
    "Grant",
    "Guadalupe",
    "Harding",
    "Hidalgo",
    "Lea",
    "Lincoln",
    "Los Alamos",
    "Luna",
    "McKinley",
    "Mora",
    "Otero",
    "Quay",
    "Rio Arriba",
    "Roosevelt",
    "San Juan",
    "San Miguel",
    "Sandoval",
    "Santa Fe",
    "Sierra",
    "Socorro",
    "Taos",
    "Torrance",
    "Union",
    "Valencia" ) ),
( 'New York', (
    "Albany",
    "Allegany",
    "Bronx",
    "Broome",
    "Cattaraugus",
    "Cayuga",
    "Chautauqua",
    "Chemung",
    "Chenango",
    "Clinton",
    "Columbia",
    "Cortland",
    "Delaware",
    "Dutchess",
    "Erie",
    "Essex",
    "Franklin",
    "Fulton",
    "Genesee",
    "Greene",
    "Hamilton",
    "Herkimer",
    "Jefferson",
    "Kings",
    "Lewis",
    "Livingston",
    "Madison",
    "Monroe",
    "Montgomery",
    "Nassau",
    "New York",
    "Niagara",
    "Oneida",
    "Onondaga",
    "Ontario",
    "Orange",
    "Orleans",
    "Oswego",
    "Otsego",
    "Putnam",
    "Queens",
    "Rensselaer",
    "Richmond",
    "Rockland",
    "Saratoga",
    "Schenectady",
    "Schoharie",
    "Schuyler",
    "Seneca",
    "St. Lawrence",
    "Steuben",
    "Suffolk",
    "Sullivan",
    "Tioga",
    "Tompkins",
    "Ulster",
    "Warren",
    "Washington",
    "Wayne",
    "Westchester",
    "Wyoming",
    "Yates" ) ),
( 'North Carolina', (
    "Alamance",
    "Alexander",
    "Alleghany",
    "Anson",
    "Ashe",
    "Avery",
    "Beaufort",
    "Bertie",
    "Bladen",
    "Brunswick",
    "Buncombe",
    "Burke",
    "Cabarrus",
    "Caldwell",
    "Camden",
    "Carteret",
    "Caswell",
    "Catawba",
    "Chatham",
    "Cherokee",
    "Chowan",
    "Clay",
    "Cleveland",
    "Columbus",
    "Craven",
    "Cumberland",
    "Currituck",
    "Dare",
    "Davidson",
    "Davie",
    "Duplin",
    "Durham",
    "Edgecombe",
    "Forsyth",
    "Franklin",
    "Gaston",
    "Gates",
    "Graham",
    "Granville",
    "Greene",
    "Guilford",
    "Halifax",
    "Harnett",
    "Haywood",
    "Henderson",
    "Hertford",
    "Hoke",
    "Hyde",
    "Iredell",
    "Jackson",
    "Johnston",
    "Jones",
    "Lee",
    "Lenoir",
    "Lincoln",
    "Macon",
    "Madison",
    "Martin",
    "McDowell",
    "Mecklenburg",
    "Mitchell",
    "Montgomery",
    "Moore",
    "Nash",
    "New Hanover",
    "Northampton",
    "Onslow",
    "Orange",
    "Pamlico",
    "Pasquotank",
    "Pender",
    "Perquimans",
    "Person",
    "Pitt",
    "Polk",
    "Randolph",
    "Richmond",
    "Robeson",
    "Rockingham",
    "Rowan",
    "Rutherford",
    "Sampson",
    "Scotland",
    "Stanly",
    "Stokes",
    "Surry",
    "Swain",
    "Transylvania",
    "Tyrrell",
    "Union",
    "Vance",
    "Wake",
    "Warren",
    "Washington",
    "Watauga",
    "Wayne",
    "Wilkes",
    "Wilson",
    "Yadkin",
    "Yancey" ) ),
( 'North Dakota', (
    "Adams",
    "Barnes",
    "Benson",
    "Billings",
    "Bottineau",
    "Bowman",
    "Burke",
    "Burleigh",
    "Cass",
    "Cavalier",
    "Dickey",
    "Divide",
    "Dunn",
    "Eddy",
    "Emmons",
    "Foster",
    "Golden Valley",
    "Grand Forks",
    "Grant",
    "Griggs",
    "Hettinger",
    "Kidder",
    "LaMoure",
    "Logan",
    "McHenry",
    "McIntosh",
    "McKenzie",
    "McLean",
    "Mercer",
    "Morton",
    "Mountrail",
    "Nelson",
    "Oliver",
    "Pembina",
    "Pierce",
    "Ramsey",
    "Ransom",
    "Renville",
    "Richland",
    "Rolette",
    "Sargent",
    "Sheridan",
    "Sioux",
    "Slope",
    "Stark",
    "Steele",
    "Stutsman",
    "Towner",
    "Traill",
    "Walsh",
    "Ward",
    "Wells",
    "Williams" ) ),
( 'Ohio', (
    "Adams",
    "Allen",
    "Ashland",
    "Ashtabula",
    "Athens",
    "Auglaize",
    "Belmont",
    "Brown",
    "Butler",
    "Carroll",
    "Champaign",
    "Clark",
    "Clermont",
    "Clinton",
    "Columbiana",
    "Coshocton",
    "Crawford",
    "Cuyahoga",
    "Darke",
    "Defiance",
    "Delaware",
    "Erie",
    "Fairfield",
    "Fayette",
    "Franklin",
    "Fulton",
    "Gallia",
    "Geauga",
    "Greene",
    "Guernsey",
    "Hamilton",
    "Hancock",
    "Hardin",
    "Harrison",
    "Henry",
    "Highland",
    "Hocking",
    "Holmes",
    "Huron",
    "Jackson",
    "Jefferson",
    "Knox",
    "Lake",
    "Lawrence",
    "Licking",
    "Logan",
    "Lorain",
    "Lucas",
    "Madison",
    "Mahoning",
    "Marion",
    "Medina",
    "Meigs",
    "Mercer",
    "Miami",
    "Monroe",
    "Montgomery",
    "Morgan",
    "Morrow",
    "Muskingum",
    "Noble",
    "Ottawa",
    "Paulding",
    "Perry",
    "Pickaway",
    "Pike",
    "Portage",
    "Preble",
    "Putnam",
    "Richland",
    "Ross",
    "Sandusky",
    "Scioto",
    "Seneca",
    "Shelby",
    "Stark",
    "Summit",
    "Trumbull",
    "Tuscarawas",
    "Union",
    "Van Wert",
    "Vinton",
    "Warren",
    "Washington",
    "Wayne",
    "Williams",
    "Wood",
    "Wyandot" ) ),
( 'Oklahoma', (
    "Adair",
    "Alfalfa",
    "Atoka",
    "Beaver",
    "Beckham",
    "Blaine",
    "Bryan",
    "Caddo",
    "Canadian",
    "Carter",
    "Cherokee",
    "Choctaw",
    "Cimarron",
    "Cleveland",
    "Coal",
    "Comanche",
    "Cotton",
    "Craig",
    "Creek",
    "Custer",
    "Delaware",
    "Dewey",
    "Ellis",
    "Garfield",
    "Garvin",
    "Grady",
    "Grant",
    "Greer",
    "Harmon",
    "Harper",
    "Haskell",
    "Hughes",
    "Jackson",
    "Jefferson",
    "Johnston",
    "Kay",
    "Kingfisher",
    "Kiowa",
    "Latimer",
    "Le Flore",
    "Lincoln",
    "Logan",
    "Love",
    "Major",
    "Marshall",
    "Mayes",
    "McClain",
    "McCurtain",
    "McIntosh",
    "Murray",
    "Muskogee",
    "Noble",
    "Nowata",
    "Okfuskee",
    "Oklahoma",
    "Okmulgee",
    "Osage",
    "Ottawa",
    "Pawnee",
    "Payne",
    "Pittsburg",
    "Pontotoc",
    "Pottawatomie",
    "Pushmataha",
    "Roger Mills",
    "Rogers",
    "Seminole",
    "Sequoyah",
    "Stephens",
    "Texas",
    "Tillman",
    "Tulsa",
    "Wagoner",
    "Washington",
    "Washita",
    "Woods",
    "Woodward" ) ),
( 'Oregon', (
    "Baker",
    "Benton",
    "Clackamas",
    "Clatsop",
    "Columbia",
    "Coos",
    "Crook",
    "Curry",
    "Deschutes",
    "Douglas",
    "Gilliam",
    "Grant",
    "Harney",
    "Hood River",
    "Jackson",
    "Jefferson",
    "Josephine",
    "Klamath",
    "Lake",
    "Lane",
    "Lincoln",
    "Linn",
    "Malheur",
    "Marion",
    "Morrow",
    "Multnomah",
    "Polk",
    "Sherman",
    "Tillamook",
    "Umatilla",
    "Union",
    "Wallowa",
    "Wasco",
    "Washington",
    "Wheeler",
    "Yamhill" ) ),
( 'Pennsylvania', (
    "Adams",
    "Allegheny",
    "Armstrong",
    "Beaver",
    "Bedford",
    "Berks",
    "Blair",
    "Bradford",
    "Bucks",
    "Butler",
    "Cambria",
    "Cameron",
    "Carbon",
    "Centre",
    "Chester",
    "Clarion",
    "Clearfield",
    "Clinton",
    "Columbia",
    "Crawford",
    "Cumberland",
    "Dauphin",
    "Delaware",
    "Elk",
    "Erie",
    "Fayette",
    "Forest",
    "Franklin",
    "Fulton",
    "Greene",
    "Huntingdon",
    "Indiana",
    "Jefferson",
    "Juniata",
    "Lackawanna",
    "Lancaster",
    "Lawrence",
    "Lebanon",
    "Lehigh",
    "Luzerne",
    "Lycoming",
    "McKean",
    "Mercer",
    "Mifflin",
    "Monroe",
    "Montgomery",
    "Montour",
    "Northampton",
    "Northumberland",
    "Perry",
    "Philadelphia",
    "Pike",
    "Potter",
    "Schuylkill",
    "Snyder",
    "Somerset",
    "Sullivan",
    "Susquehanna",
    "Tioga",
    "Union",
    "Venango",
    "Warren",
    "Washington",
    "Wayne",
    "Westmoreland",
    "Wyoming",
    "York" ) ),
( 'Rhode Island', (
    "Bristol",
    "Kent",
    "Newport",
    "Providence",
    "Washington" ) ),
( 'South Carolina', (
    "Abbeville",
    "Aiken",
    "Allendale",
    "Anderson",
    "Bamberg",
    "Barnwell",
    "Beaufort",
    "Berkeley",
    "Calhoun",
    "Charleston",
    "Cherokee",
    "Chester",
    "Chesterfield",
    "Clarendon",
    "Colleton",
    "Darlington",
    "Dillon",
    "Dorchester",
    "Edgefield",
    "Fairfield",
    "Florence",
    "Georgetown",
    "Greenville",
    "Greenwood",
    "Hampton",
    "Horry",
    "Jasper",
    "Kershaw",
    "Lancaster",
    "Laurens",
    "Lee",
    "Lexington",
    "Marion",
    "Marlboro",
    "McCormick",
    "Newberry",
    "Oconee",
    "Orangeburg",
    "Pickens",
    "Richland",
    "Saluda",
    "Spartanburg",
    "Sumter",
    "Union",
    "Williamsburg",
    "York" ) ),
( 'South Dakota', (
    "Aurora",
    "Beadle",
    "Bennett",
    "Bon Homme",
    "Brookings",
    "Brown",
    "Brule",
    "Buffalo",
    "Butte",
    "Campbell",
    "Charles Mix",
    "Clark",
    "Clay",
    "Codington",
    "Corson",
    "Custer",
    "Davison",
    "Day",
    "Deuel",
    "Dewey",
    "Douglas",
    "Edmunds",
    "Fall River",
    "Faulk",
    "Grant",
    "Gregory",
    "Haakon",
    "Hamlin",
    "Hand",
    "Hanson",
    "Harding",
    "Hughes",
    "Hutchinson",
    "Hyde",
    "Jackson",
    "Jerauld",
    "Jones",
    "Kingsbury",
    "Lake",
    "Lawrence",
    "Lincoln",
    "Lyman",
    "Marshall",
    "McCook",
    "McPherson",
    "Meade",
    "Mellette",
    "Miner",
    "Minnehaha",
    "Moody",
    "Pennington",
    "Perkins",
    "Potter",
    "Roberts",
    "Sanborn",
    "Shannon",
    "Spink",
    "Stanley",
    "Sully",
    "Todd",
    "Tripp",
    "Turner",
    "Union",
    "Walworth",
    "Yankton",
    "Ziebach" ) ),
( 'Tennessee', (
    "Anderson",
    "Bedford",
    "Benton",
    "Bledsoe",
    "Blount",
    "Bradley",
    "Campbell",
    "Cannon",
    "Carroll",
    "Carter",
    "Cheatham",
    "Chester",
    "Claiborne",
    "Clay",
    "Cocke",
    "Coffee",
    "Crockett",
    "Cumberland",
    "Davidson",
    "Decatur",
    "DeKalb",
    "Dickson",
    "Dyer",
    "Fayette",
    "Fentress",
    "Franklin",
    "Gibson",
    "Giles",
    "Grainger",
    "Greene",
    "Grundy",
    "Hamblen",
    "Hamilton",
    "Hancock",
    "Hardeman",
    "Hardin",
    "Hawkins",
    "Haywood",
    "Henderson",
    "Henry",
    "Hickman",
    "Houston",
    "Humphreys",
    "Jackson",
    "Jefferson",
    "Johnson",
    "Knox",
    "Lake",
    "Lauderdale",
    "Lawrence",
    "Lewis",
    "Lincoln",
    "Loudon",
    "Macon",
    "Madison",
    "Marion",
    "Marshall",
    "Maury",
    "McMinn",
    "McNairy",
    "Meigs",
    "Monroe",
    "Montgomery",
    "Moore",
    "Morgan",
    "Obion",
    "Overton",
    "Perry",
    "Pickett",
    "Polk",
    "Putnam",
    "Rhea",
    "Roane",
    "Robertson",
    "Rutherford",
    "Scott",
    "Sequatchie",
    "Sevier",
    "Shelby",
    "Smith",
    "Stewart",
    "Sullivan",
    "Sumner",
    "Tipton",
    "Trousdale",
    "Unicoi",
    "Union",
    "Van Buren",
    "Warren",
    "Washington",
    "Wayne",
    "Weakley",
    "White",
    "Williamson",
    "Wilson" ) ),
( 'Texas', (
    "Anderson",
    "Andrews",
    "Angelina",
    "Aransas",
    "Archer",
    "Armstrong",
    "Atascosa",
    "Austin",
    "Bailey",
    "Bandera",
    "Bastrop",
    "Baylor",
    "Bee",
    "Bell",
    "Bexar",
    "Blanco",
    "Borden",
    "Bosque",
    "Bowie",
    "Brazoria",
    "Brazos",
    "Brewster",
    "Briscoe",
    "Brooks",
    "Brown",
    "Burleson",
    "Burnet",
    "Caldwell",
    "Calhoun",
    "Callahan",
    "Cameron",
    "Camp",
    "Carson",
    "Cass",
    "Castro",
    "Chambers",
    "Cherokee",
    "Childress",
    "Clay",
    "Cochran",
    "Coke",
    "Coleman",
    "Collin",
    "Collingsworth",
    "Colorado",
    "Comal",
    "Comanche",
    "Concho",
    "Cooke",
    "Coryell",
    "Cottle",
    "Crane",
    "Crockett",
    "Crosby",
    "Culberson",
    "Dallam",
    "Dallas",
    "Dawson",
    "Deaf Smith",
    "Delta",
    "Denton",
    "DeWitt",
    "Dickens",
    "Dimmit",
    "Donley",
    "Duval",
    "Eastland",
    "Ector",
    "Edwards",
    "El Paso",
    "Ellis",
    "Erath",
    "Falls",
    "Fannin",
    "Fayette",
    "Fisher",
    "Floyd",
    "Foard",
    "Fort Bend",
    "Franklin",
    "Freestone",
    "Frio",
    "Gaines",
    "Galveston",
    "Garza",
    "Gillespie",
    "Glasscock",
    "Goliad",
    "Gonzales",
    "Gray",
    "Grayson",
    "Gregg",
    "Grimes",
    "Guadalupe",
    "Hale",
    "Hall",
    "Hamilton",
    "Hansford",
    "Hardeman",
    "Hardin",
    "Harris",
    "Harrison",
    "Hartley",
    "Haskell",
    "Hays",
    "Hemphill",
    "Henderson",
    "Hidalgo",
    "Hill",
    "Hockley",
    "Hood",
    "Hopkins",
    "Houston",
    "Howard",
    "Hudspeth",
    "Hunt",
    "Hutchinson",
    "Irion",
    "Jack",
    "Jackson",
    "Jasper",
    "Jeff Davis",
    "Jefferson",
    "Jim Hogg",
    "Jim Wells",
    "Johnson",
    "Jones",
    "Karnes",
    "Kaufman",
    "Kendall",
    "Kenedy",
    "Kent",
    "Kerr",
    "Kimble",
    "King",
    "Kinney",
    "Kleberg",
    "Knox",
    "La Salle",
    "Lamar",
    "Lamb",
    "Lampasas",
    "Lavaca",
    "Lee",
    "Leon",
    "Liberty",
    "Limestone",
    "Lipscomb",
    "Live Oak",
    "Llano",
    "Loving",
    "Lubbock",
    "Lynn",
    "Madison",
    "Marion",
    "Martin",
    "Mason",
    "Matagorda",
    "Maverick",
    "McCulloch",
    "McLennan",
    "McMullen",
    "Medina",
    "Menard",
    "Midland",
    "Milam",
    "Mills",
    "Mitchell",
    "Montague",
    "Montgomery",
    "Moore",
    "Morris",
    "Motley",
    "Nacogdoches",
    "Navarro",
    "Newton",
    "Nolan",
    "Nueces",
    "Ochiltree",
    "Oldham",
    "Orange",
    "Palo Pinto",
    "Panola",
    "Parker",
    "Parmer",
    "Pecos",
    "Polk",
    "Potter",
    "Presidio",
    "Rains",
    "Randall",
    "Reagan",
    "Real",
    "Red River",
    "Reeves",
    "Refugio",
    "Roberts",
    "Robertson",
    "Rockwall",
    "Runnels",
    "Rusk",
    "Sabine",
    "San Augustine",
    "San Jacinto",
    "San Patricio",
    "San Saba",
    "Schleicher",
    "Scurry",
    "Shackelford",
    "Shelby",
    "Sherman",
    "Smith",
    "Somervell",
    "Starr",
    "Stephens",
    "Sterling",
    "Stonewall",
    "Sutton",
    "Swisher",
    "Tarrant",
    "Taylor",
    "Terrell",
    "Terry",
    "Throckmorton",
    "Titus",
    "Tom Green",
    "Travis",
    "Trinity",
    "Tyler",
    "Upshur",
    "Upton",
    "Uvalde",
    "Val Verde",
    "Van Zandt",
    "Victoria",
    "Walker",
    "Waller",
    "Ward",
    "Washington",
    "Webb",
    "Wharton",
    "Wheeler",
    "Wichita",
    "Wilbarger",
    "Willacy",
    "Williamson",
    "Wilson",
    "Winkler",
    "Wise",
    "Wood",
    "Yoakum",
    "Young",
    "Zapata",
    "Zavala" ) ),
( 'Utah', (
    "Beaver",
    "Box Elder",
    "Cache",
    "Carbon",
    "Daggett",
    "Davis",
    "Duchesne",
    "Emery",
    "Garfield",
    "Grand",
    "Iron",
    "Juab",
    "Kane",
    "Millard",
    "Morgan",
    "Piute",
    "Rich",
    "Salt Lake",
    "San Juan",
    "Sanpete",
    "Sevier",
    "Summit",
    "Tooele",
    "Uintah",
    "Utah",
    "Wasatch",
    "Washington",
    "Wayne",
    "Weber" ) ),
( 'Vermont', (
    "Addison",
    "Bennington",
    "Caledonia",
    "Chittenden",
    "Essex",
    "Franklin",
    "Grand Isle",
    "Lamoille",
    "Orange",
    "Orleans",
    "Rutland",
    "Washington",
    "Windham",
    "Windsor" ) ),
( 'Virginia', (
    "Accomack",
    "Albemarle",
    "Alleghany",
    "Amelia",
    "Amherst",
    "Appomattox",
    "Arlington",
    "Augusta",
    "Bath",
    "Bedford",
    "Bland",
    "Botetourt",
    "Brunswick",
    "Buchanan",
    "Buckingham",
    "Campbell",
    "Caroline",
    "Carroll",
    "Charles City",
    "Charlotte",
    "Chesterfield",
    "Clarke",
    "Craig",
    "Culpeper",
    "Cumberland",
    "Dickenson",
    "Dinwiddie",
    "Essex",
    "Fairfax",
    "Fauquier",
    "Floyd",
    "Fluvanna",
    "Franklin",
    "Frederick",
    "Giles",
    "Gloucester",
    "Goochland",
    "Grayson",
    "Greene",
    "Greensville",
    "Halifax",
    "Hanover",
    "Henrico",
    "Henry",
    "Highland",
    "Isle of Wight",
    "James City",
    "King and Queen",
    "King George",
    "King William",
    "Lancaster",
    "Lee",
    "Loudoun",
    "Louisa",
    "Lunenburg",
    "Madison",
    "Mathews",
    "Mecklenburg",
    "Middlesex",
    "Montgomery",
    "Nelson",
    "New Kent",
    "Northampton",
    "Northumberland",
    "Nottoway",
    "Orange",
    "Page",
    "Patrick",
    "Pittsylvania",
    "Powhatan",
    "Prince Edward",
    "Prince George",
    "Prince William",
    "Pulaski",
    "Rappahannock",
    "Richmond",
    "Roanoke",
    "Rockbridge",
    "Rockingham",
    "Russell",
    "Scott",
    "Shenandoah",
    "Smyth",
    "Southampton",
    "Spotsylvania",
    "Stafford",
    "Surry",
    "Sussex",
    "Tazewell",
    "Warren",
    "Washington",
    "Westmoreland",
    "Wise",
    "Wythe",
    "York" ) ),
( 'Washington', (
    "Adams",
    "Asotin",
    "Benton",
    "Chelan",
    "Clallam",
    "Clark",
    "Columbia",
    "Cowlitz",
    "Douglas",
    "Ferry",
    "Franklin",
    "Garfield",
    "Grant",
    "Grays Harbor",
    "Island",
    "Jefferson",
    "King",
    "Kitsap",
    "Kittitas",
    "Klickitat",
    "Lewis",
    "Lincoln",
    "Mason",
    "Okanogan",
    "Pacific",
    "Pend Oreille",
    "Pierce",
    "San Juan",
    "Skagit",
    "Skamania",
    "Snohomish",
    "Spokane",
    "Stevens",
    "Thurston",
    "Wahkiakum",
    "Walla Walla",
    "Whatcom",
    "Whitman",
    "Yakima" ) ),
( 'West Virginia', (
    "Barbour",
    "Berkeley",
    "Boone",
    "Braxton",
    "Brooke",
    "Cabell",
    "Calhoun",
    "Clay",
    "Doddridge",
    "Fayette",
    "Gilmer",
    "Grant",
    "Greenbrier",
    "Hampshire",
    "Hancock",
    "Hardy",
    "Harrison",
    "Jackson",
    "Jefferson",
    "Kanawha",
    "Lewis",
    "Lincoln",
    "Logan",
    "Marion",
    "Marshall",
    "Mason",
    "McDowell",
    "Mercer",
    "Mineral",
    "Mingo",
    "Monongalia",
    "Monroe",
    "Morgan",
    "Nicholas",
    "Ohio",
    "Pendleton",
    "Pleasants",
    "Pocahontas",
    "Preston",
    "Putnam",
    "Raleigh",
    "Randolph",
    "Ritchie",
    "Roane",
    "Summers",
    "Taylor",
    "Tucker",
    "Tyler",
    "Upshur",
    "Wayne",
    "Webster",
    "Wetzel",
    "Wirt",
    "Wood",
    "Wyoming" ) ),
( 'Wisconsin', (
    "Adams",
    "Ashland",
    "Barron",
    "Bayfield",
    "Brown",
    "Buffalo",
    "Burnett",
    "Calumet",
    "Chippewa",
    "Clark",
    "Columbia",
    "Crawford",
    "Dane",
    "Dodge",
    "Door",
    "Douglas",
    "Dunn",
    "Eau Claire",
    "Florence",
    "Fond du Lac",
    "Forest",
    "Grant",
    "Green",
    "Green Lake",
    "Iowa",
    "Iron",
    "Jackson",
    "Jefferson",
    "Juneau",
    "Kenosha",
    "Kewaunee",
    "La Crosse",
    "Lafayette",
    "Langlade",
    "Lincoln",
    "Manitowoc",
    "Marathon",
    "Marinette",
    "Marquette",
    "Menominee",
    "Milwaukee",
    "Monroe",
    "Oconto",
    "Oneida",
    "Outagamie",
    "Ozaukee",
    "Pepin",
    "Pierce",
    "Polk",
    "Portage",
    "Price",
    "Racine",
    "Richland",
    "Rock",
    "Rusk",
    "Sauk",
    "Sawyer",
    "Shawano",
    "Sheboygan",
    "St. Croix",
    "Taylor",
    "Trempealeau",
    "Vernon",
    "Vilas",
    "Walworth",
    "Washburn",
    "Washington",
    "Waukesha",
    "Waupaca",
    "Waushara",
    "Winnebago",
    "Wood" ) ),
( 'Wyoming', (
    "Albany",
    "Big Horn",
    "Campbell",
    "Carbon",
    "Converse",
    "Crook",
    "Fremont",
    "Goshen",
    "Hot Springs",
    "Johnson",
    "Laramie",
    "Lincoln",
    "Natrona",
    "Niobrara",
    "Park",
    "Platte",
    "Sheridan",
    "Sublette",
    "Sweetwater",
    "Teton",
    "Uinta",
    "Washakie",
    "Weston" ) )
)
 
